apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-clearsessions-container
            image: docker.io/library/django:1
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - configMapRef:
                  name: django-config
          restartPolicy: OnFailure
