apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: django
        image: docker.io/library/django:1
        command: ["python", "manage.py", "migrate", "--noinput"]
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: django-config
      restartPolicy: Never
  backoffLimit: 4
